[default]
extend-ignore-re = [
    # Ignore Cyrillic and CJK text, and any markdown links that might trigger typos
    "(?i)[а-яё]",
    "[\u4e00-\u9fff]",
]

[default.extend-words]
Savin = "Savin"
[files]
extend-exclude = [
    "*.graphml",
    "*.svg",
    ".lycheecache"
]
