name: Check links

on:
  pull_request:
  schedule:
    # Every Monday at 06:00 UTC
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links in markdown files
        uses: lycheeverse/lychee-action@v2
        id: lychee
        with:
          args: >-
            --no-progress
            --accept 200..=204,429
            --max-retries 2
            --timeout 45
            --cache
            --max-cache-age 1d
            "**/*.md"
          fail: true
          output: ./lychee/out.md

      - name: Create Issue From File
        if: failure() && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
